language: python
install:
  - pip install pyyaml
  - pip install -r requirements-oscar2.txt
  - pip install coveralls
python:
  - "2.7"
before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - export DISPLAY=:99.0
  - psql -c "CREATE DATABASE oscar;" -U postgres
  - psql -c "CREATE USER oscar WITH PASSWORD 'oscar' CREATEDB;" -U postgres
  - python manage.py makemigrations
  - chmod +x makemigrations.sh
  - ./makemigrations.sh
  - python manage.py migrate
  - sh -e /etc/init.d/xvfb start
script:
  - python validate_exercices.py
  - python manage.py test
  - coverage run --source=forum manage.py test forum
after_success:
  coveralls
services:
  - postgresql
addons:
  postgresql: "9.4"
  firefox: "45.4.0esr"
notifications:
  email: false
